enum recEnum {
    MODEL,
    RENDER_PASS,
    OBJECT_LAYOUT,
    GRAPHIC_PIPELINES,
    GRAPHIC_PIPELINE_LAYOUTS,
    ENTITIES,
    SCREEN,
    COMMAND_QUEUE,

    MODEL_1 = 0,

    RENDER_PASS_CLEAN = 0,
    RENDER_PASS_STAY,

    OBJECT_LAYOUT_OBJECT = 0,
    OBJECT_LAYOUT_CAMERA,

    GRAPHIC_PIPELINES_1 = 0,

    GRAPHIC_PIPELINE_LAYOUT_1 = 0,

    ENTITIES_1 = 0,

    SCREEN_1 = 0,

    COMMAND_QUEUE_GRAPHICS = 0,
};
