enum recEnum {
    MODEL,
    RENDER_PASS,
    OBJECT_LAYOUT,
    GRAPHIC_PIPELINES,
    GRAPHIC_PIPELINE_LAYOUTS,
    ENTITIES,
    SCREEN,
    COMMAND_QUEUE,
    WRITE_TEXTURE,
    DESCRIPTOR_COMP,
    DESCRIPTOR_FRAG,
    CAMERA_BUFFER,
    CAMERA_DESCRIPTOR,

    MODEL_1 = 0,

    RENDER_PASS_CLEAN = 0,
    RENDER_PASS_STAY,

    OBJECT_LAYOUT_OBJECT = 0,
    OBJECT_LAYOUT_CAMERA,
    OBJECT_LAYOUT_COMPUTE,
    OBJECT_LAYOUT_TEXTURE,

    GRAPHIC_PIPELINES_1 = 0,
    COMPUTE_PIPELINE,

    PIPELINE_LAYOUT_GRAPHICS = 0,
    PIPELINE_LAYOUT_COMPUTE,

    ENTITIES_1 = 0,

    SCREEN_1 = 0,

    COMMAND_QUEUE_GRAPHICS = 0,
    COMMAND_QUEUE_COMPUTE,
};
